[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_fpl = "8j5Fm6UKtk7rV4xZGXEQZcHZnSKqxx6aEeSkHEac7K2W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
